spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: true

    #spring.datasource.url=jdbc:mysql://localhost:3306/test?useSSL=false
    #spring.datasource.username=root
    #spring.datasource.password=root
    #spring.jpa.generate-ddl=true